//THIS FILE IS ONLY USED FOR SEEDING THE DATABASE, ALL OTHER FILES SHOULD USE THE GETDB FUNCTION IN THE DB.JS FILE TO GET THE DATABASE CONNECTION. THIS FILE IS NOT USED FOR ANYTHING ELSE.
export const mongoConfig = {
  serverUrl: 'mongodb://localhost:27017/',
  database: 'BiteCheckDB'
};
